version: '3.8'

services:
  # Database Utama (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: hired_hero_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hired_hero
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Queue & Cache (Redis)
  redis:
    image: redis:7-alpine
    container_name: hired_hero_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: